const path = require('path');
const fs = require('fs-extra');

async function saveLatexFiles(projectPath, latexContent) {
  const outputDir = path.join(projectPath, 'HardPaper-Output');
  await fs.ensureDir(outputDir);

  await fs.writeFile(path.join(outputDir, 'Final_Manuscript.tex'), latexContent, 'utf-8');

  const bibContent = `@misc{project2024,
  author = {Author},
  title = {Project Documentation},
  year = {2024},
  note = {Generated by HardPaper}
}`;
  await fs.writeFile(path.join(outputDir, 'references.bib'), bibContent, 'utf-8');

  return outputDir;
}

module.exports = { saveLatexFiles };